name: Run tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.15-dev"]#, "3.15t-dev"]
        os: [ubuntu-latest, windows-latest]
        experimental: [false]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Test using tox
        run: tox -e py
